# Cloudflare Pages configuration
name = "10x-cards"
compatibility_date = "2023-11-15"
main = "worker-polyfill.js"

# Build settings
[build]
command = "npm run build"

# Output directory (required for Pages)
[site]
bucket = "./dist"

# This is crucial for Cloudflare Pages to find the build output
[build.upload]
format = "directory"

# Add KV namespace binding for sessions
[[kv_namespaces]]
binding = "SESSION"
id = "your-kv-namespace-id" # Replace with actual KV namespace ID once created

# Redirects and routes
[env.production]
routes = [
  { pattern = "*", zone_name = "your-domain.com" }
]

[env.staging]
name = "10x-cards-staging" 